### ISSUE TITLE
Method not found: 'MongoDB.Driver.Builders.CollectionOptionsBuilder

### ISSUE THREAD

**Issue by razorsmith** [CaptainCodeman/elmah-mongodb#2]
This is a simple one and is caused by a mismatch on the 10gen driver versions.

Rebuilding the Elmah-mongodb using the correct/latest drivers (MongoDB.Bson, MongoDB.Driver) will fix this.

Cheers CaptainCodeman...........legend!

**Comment by CaptainCodeman** [comment]
Thanks !

Updated driver to 1.3 and pushed to NuGet
